#!/bin/sh
GIT_GRAPH_ASKPASS_PIPE=`mktemp`
GIT_GRAPH_ASKPASS_PIPE="$GIT_GRAPH_ASKPASS_PIPE" "$GIT_GRAPH_ASKPASS_NODE" "$GIT_GRAPH_ASKPASS_MAIN" $*
cat $GIT_GRAPH_ASKPASS_PIPE
rm $GIT_GRAPH_ASKPASS_PIPE