// Generates electron/ui/icons.js from Phosphor icons (https://phosphoricons.com, MIT).
// Usage: node scripts/build-icons.js <path-to-@phosphor-icons/core>
// Add a name to ICONS (a Phosphor icon file name, without extension), re-run, commit the result.
const fs = require('fs');
const path = require('path');

const core = process.argv[2];
if (!core) { console.error('usage: node scripts/build-icons.js <path to @phosphor-icons/core>'); process.exit(1); }

const ICONS = [
	// git
	'git-branch', 'git-merge', 'git-commit', 'git-pull-request', 'git-diff', 'git-fork', 'tag', 'stack', 'archive-box',
	// arrows / sync
	'arrow-down', 'arrow-up', 'arrow-left', 'arrow-right', 'arrows-clockwise', 'arrow-counter-clockwise', 'arrow-u-up-left',
	'arrow-square-out', 'caret-down', 'caret-up', 'caret-left', 'caret-right', 'cloud-arrow-down', 'cloud-arrow-up', 'download-simple', 'upload-simple',
	// files / folders
	'folder-open', 'folder-simple', 'folder-plus', 'file', 'file-plus', 'file-minus', 'file-text', 'file-dashed', 'hard-drives',
	// actions
	'plus', 'minus', 'x', 'check', 'trash', 'pencil-simple', 'copy', 'copy-simple', 'magnifying-glass', 'funnel', 'dots-three', 'dots-three-vertical',
	'play', 'stop', 'sparkle', 'gear', 'gear-six', 'house', 'terminal-window', 'link-simple', 'lock-simple', 'eye', 'eye-slash', 'clipboard',
	'sort-ascending', 'list', 'rows', 'columns', 'push-pin', 'star', 'clock', 'user', 'users', 'bug', 'wrench', 'scissors', 'sidebar-simple', 'sign-out',
	// status
	'check-circle', 'x-circle', 'warning', 'warning-circle', 'info', 'circle', 'circle-notch', 'lightning', 'rocket-launch',
	// brands
	'github-logo', 'gitlab-logo', 'microsoft-windows-logo'
];

const out = {};
const missing = [];
for (const name of ICONS) {
	const file = path.join(core, 'assets', 'regular', name + '.svg');
	if (!fs.existsSync(file)) { missing.push(name); continue; }
	// Strip the fixed 256 viewBox size attributes so CSS controls size; keep fill="currentColor" so icons take the text color.
	out[name] = fs.readFileSync(file, 'utf8').trim()
		.replace(/<svg[^>]*>/, '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true" focusable="false">')
		.replace(/\s+/g, ' ');
}
if (missing.length) console.warn('Missing icons (skipped):', missing.join(', '));

const js = `// GENERATED by scripts/build-icons.js - do not edit. Phosphor icons (MIT), regular weight.
// Usage: <i data-icon="git-branch"></i> (auto-hydrated, also for nodes added later) or GG.icon('git-branch').
(function () {
	'use strict';
	var icons = ${JSON.stringify(out, null, 1).replace(/\n\s*/g, '\n')};
	var GG = window.GG = window.GG || {};
	GG.icons = icons;
	GG.icon = function (name, cls) {
		var svg = icons[name];
		if (!svg) return '';
		return cls ? svg.replace('<svg ', '<svg class="' + cls + '" ') : svg;
	};
	function hydrate(root) {
		var nodes = (root.querySelectorAll ? root.querySelectorAll('[data-icon]:not([data-icon-done])') : []);
		for (var i = 0; i < nodes.length; i++) {
			var el = nodes[i], svg = icons[el.getAttribute('data-icon')];
			el.setAttribute('data-icon-done', '1');
			if (svg) el.innerHTML = svg;
		}
	}
	GG.hydrateIcons = hydrate;
	function start() {
		hydrate(document);
		new MutationObserver(function (muts) {
			for (var i = 0; i < muts.length; i++) {
				for (var j = 0; j < muts[i].addedNodes.length; j++) {
					var n = muts[i].addedNodes[j];
					if (n.nodeType === 1) { if (n.hasAttribute('data-icon') && !n.hasAttribute('data-icon-done')) hydrate({ querySelectorAll: function () { return [n]; } }); hydrate(n); }
				}
			}
		}).observe(document.documentElement, { childList: true, subtree: true });
	}
	if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start); else start();
})();
`;
fs.mkdirSync(path.join(__dirname, '..', 'electron', 'ui'), { recursive: true });
fs.writeFileSync(path.join(__dirname, '..', 'electron', 'ui', 'icons.js'), js);
console.log('wrote electron/ui/icons.js with', Object.keys(out).length, 'icons');
